Azure-ServiceBus-MsgReceiver/Models/Queue.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace Azure_ServiceBus_MsgReceiver.Models
{
    [DataContract(Name = "Queue", Namespace = "Queue")]
    public class Queue
    {
        [DataMember]
        public int Count { get; set; }
        [DataMember]
        public string Message { get; set; }
    }
}

Azure-ServiceBus-MsgReceiver/Models/Receiver.cs
using Microsoft.ServiceBus.Messaging;
using System;
using System.Configuration;
using System.Diagnostics;

namespace Azure_ServiceBus_MsgReceiver.Models
{
    public class Receiver
    {
        Queue msg;
       
        public Queue ReceiveMessage()
        {
            string connString = ConfigurationSettings.AppSettings["Microsoft.ServiceBus.ConnectionString"];

            QueueClient qClient = QueueClient.CreateFromConnectionString(connString, "qservice", ReceiveMode.PeekLock);
            var messages = qClient.ReceiveBatch(1);

            foreach (var item in messages)
            {
                msg = item.GetBody<Queue>();
                Console.WriteLine(msg);
                item.Complete(); //Remove Message from queue
                return msg;
            }
            return msg;
        }
    }
}

Azure-ServiceBus-MsgReceiver/Models/Sender.cs
using Microsoft.Azure.ServiceBus;
using Microsoft.ServiceBus.Messaging;
using System.Configuration;
using System.Text;
using System.Text.Json;

namespace Azure_ServiceBus_MsgReceiver.Models
{
    public class Sender
    {
        public void CreateOrder(Queue que)
        {           
            string connString = ConfigurationSettings.AppSettings["Microsoft.ServiceBus.ConnectionString"];
            Microsoft.ServiceBus.Messaging.QueueClient client = Microsoft.ServiceBus.Messaging.QueueClient.CreateFromConnectionString(connString, "qservice");
            
           BrokeredMessage message = new BrokeredMessage(que);
            /*
            string messageBody = JsonSerializer.Serialize(que);
            var message = new Message(Encoding.UTF8.GetBytes(messageBody));
            Microsoft.ServiceBus.Messaging.QueueClient.SendAsync(message);
            */

            client.SendAsync(message);
        }
            
    }
}

Azure-ServiceBus-MsgReceiver/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Azure_ServiceBus_MsgReceiver.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Azure-ServiceBus-MsgReceiver/Controllers/MessageReceiverController.cs
using Azure_ServiceBus_MsgReceiver.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Azure_ServiceBus_MsgReceiver.Controllers
{
    public class MessageReceiverController : Controller
    {
        Receiver obj;

        public MessageReceiverController()
        {
            obj = new Receiver();
        }

        // GET: 
        public ActionResult Index()
        {

            var Queue = new Queue()
            {

                Count = 1,
                Message = "Sandeep Singh Shekhawat"
            };


           /* foreach (var item in Queue)
            {
                var msg = item.GetBody<Queue>();
                Console.WriteLine(msg);
                item.Complete(); //Remove Message from queue
            }*/

            ViewBag.Data = Queue;
            return View();
        }


        [HttpPost]
        public ActionResult Index(Queue c)
        {
           Queue result = obj.ReceiveMessage();

            ViewBag.Count = result.Count;
            ViewBag.Message = result.Message;
            return View(c);
        }

    }
}

Azure-ServiceBus-MsgReceiver/Controllers/MessageSenderController.cs
using Azure_ServiceBus_MsgReceiver.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Azure_ServiceBus_MsgReceiver.Controllers
{
    public class MessageSenderController : Controller
    {
        Sender obj;

        public MessageSenderController()
        {
          obj = new Sender();
        }

        // GET: OrderManager
        public ActionResult Index()
        {
            return View("Index");
        }


        [HttpPost]
        public ActionResult Index(Queue c)
        {
            obj.CreateOrder(c);
            return View("Index");
        }
       
    }
}

Azure-ServiceBus-MsgReceiver/Controllers/ReceiveAPIController.cs
using Azure_ServiceBus_MsgReceiver.Models;
using Microsoft.ServiceBus.Messaging;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Azure_ServiceBus_MsgReceiver.Controllers
{
    public class ReceiveAPIController : ApiController
    {

        [HttpGet]
        [Route("api/qreceiver")]
        public void ReceiveMessage()
        {
            //Code for Adding Message in Queue

            //S1: The NamespaceManager object used to manage queues, topics etc.
            string connString = ConfigurationSettings.AppSettings["Microsoft.ServiceBus.ConnectionString"];

            QueueClient qClient = QueueClient.CreateFromConnectionString(connString, "qservice", ReceiveMode.PeekLock);
            //BrokeredMessage message = qClient.Receive();
           
            var messages = qClient.ReceiveBatch(1);

            

            foreach (var item in messages)
            {
                var msg=item.GetBody<Queue>();
                Console.WriteLine(msg);
                item.Complete(); //Remove Message from queue
            }//Ends Here
        }

    }
}

Azure-ServiceBus-MsgReceiver/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Azure-ServiceBus-MsgReceiver/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Azure-ServiceBus-MsgReceiver/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Azure-ServiceBus-MsgReceiver/Views/MessageReceiver/Index.cshtml
@model Azure_ServiceBus_MsgReceiver.Models.Queue

@{
    ViewBag.Title = "ServiceBus";
}

<h2>Queue Receiver</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <h3>To process the Message </h3>  <input type="submit" value="Click Here!" onclick="Rec()" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@Html.Label("Message")
<p> Count:@ViewBag.Count</p>
<p> Message:@ViewBag.Message</p>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function Rec() {
            //alert("Message Processed!!!");
        }
    </script>
}

Azure-ServiceBus-MsgReceiver/Views/MessageSender/Index.cshtml
@model Azure_ServiceBus_MsgReceiver.Models.Queue

@{
    ViewBag.Title = "ServiceBus";
}

<h2>Queue Sender</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" onclick="sub()" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function sub() {
            alert("Send");
    }

    </script>
}

Azure-ServiceBus-MsgReceiver/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ServiceBus</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ServiceBus", "Index", "MessageSender", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Send", "Index", "MessageSender")</li>
                    <li>@Html.ActionLink("Receive", "Index", "MessageReceiver")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()        
        <footer style="margin-top:450px;text-align:center">
            <hr />
            <p>&copy; @DateTime.Now.Year - ServiceBus</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>